services:
  - type: web
    name: medisphere-web
    env: python

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate

    startCommand: gunicorn MediSphere.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MediSphere.settings
      - key: DATABASE_URL
        fromDatabase:
          name: medisphere-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: medisphere-web.onrender.com

      # Optional: set these manually in Render dashboard if needed
      - key: RECAPTCHA_PUBLIC_KEY
        sync: false
      - key: RECAPTCHA_PRIVATE_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: medisphere-db
    databaseName: medisphere
    user: medisphere_user
